export const vegetableKeywords = [
  'asparagus',
  'aubergine',
  'baby plum tomatoes',
  'basil',
  'basil leaves',
  'bay leaf',
  'bay leaves',
  'broccoli',
  'brown lentils',
  'carrot',
  'carrots',
  'celeriac',
  'celery',
  'celery salt',
  'cherry tomatoes',
  'chopped onion',
  'chopped parsley',
  'chopped tomatoes',
  'cilantro',
  'cucumber',
  'egg plants',
  'fennel bulb',
  'fennel seeds',
  'green beans',
  'green chilli',
  'green olives',
  'jerusalem artichokes',
  'kale',
  'leek',
  'lettuce',
  'little gem lettuce',
  'mushrooms',
  'mustard seeds',
  'onion',
  'onions',
  'oregano',
  'parsley',
  'pitted black olives',
  'red onions',
  'red pepper',
  'rocket',
  'shallots',
  'spinach',
  'spring onions',
  'squash',
  'sweet potatoes',
  'tomatoes',
  'zucchini',
  'peas',
  'cabbage',
  'courgettes',
  'artichokes',
  'brussels sprouts',
  'cress',
  'swiss chard',
  'endive',
  'water chestnut',
  'chinese broccoli',
];

export const meatKeywords = [
  'beef',
  'beef brisket',
  'beef fillet',
  'beef shin',
  'chicken',
  'chicken breast',
  'chicken breasts',
  'chicken legs',
  'chicken thighs',
  'duck',
  'duck legs',
  'ground beef',
  'ham',
  'lamb',
  'lamb leg',
  'lamb loin chops',
  'lamb mince',
  'lamb shoulder',
  'lean minced beef',
  'minced beef',
  'minced pork',
  'pork',
  'pork chops',
  'sausages',
  'turkey mince',
  'bacon',
  'prosciutto',
  'parma ham',
  'pancetta',
  'black pudding',
];

export const fruitKeywords = [
  'apples',
  'apricot',
  'apricot jam',
  'avocado',
  'bananas',
  'blueberries',
  'blackberries',
  'cherries',
  'cranberries',
  'figs',
  'grapes',
  'kiwi',
  'lemon',
  'lemon juice',
  'lemon zest',
  'lime',
  'mango',
  'melon',
  'mulberries',
  'oranges',
  'peaches',
  'pears',
  'pineapple',
  'pomegranate',
  'raspberries',
  'strawberries',
  'watermelon',
];

export const dairyKeywords = [
  'butter',
  'cheese',
  'cheddar cheese',
  'cream',
  'creme fraiche',
  'cottage cheese',
  'feta cheese',
  'ghee',
  'gouda cheese',
  'gruyère',
  'heavy cream',
  'icing sugar',
  'mascarpone',
  'milk',
  'parmesan',
  'parmesan cheese',
  'ricotta',
  'sour cream',
  'yogurt',
  'greek yogurt',
  'full fat yogurt',
  'mozzarella',
  'ricotta',
  'brie',
  'cream cheese',
  'ice cream',
  'double cream',
  'clotted cream',
  'sour cream',
  'butter milk',
  'margarine',
];

export const grainsAndLegumesKeywords = [
  'basmati rice',
  'brown rice',
  'couscous',
  'macaroni',
  'pasta',
  'penne rigate',
  'red lentils',
  'rigatoni',
  'rice',
  'rice noodles',
  'tortillas',
  'udon noodles',
  'vermicelli',
  'whole wheat',
  'quinoa',
  'chickpeas',
  'lentils',
  'barley',
  'bulgur wheat',
  'bread rolls',
  'rye bread',
  'breadcrumbs',
];

export const condimentsAndSpicesKeywords = [
  'balsamic vinegar',
  'black pepper',
  'cacao',
  'cardamom',
  'cayenne pepper',
  'chilli powder',
  'chilli flakes',
  'cinnamon',
  'cloves',
  'cumin',
  'curry powder',
  'dill',
  'garam masala',
  'garlic',
  'garlic powder',
  'ginger',
  'ground cumin',
  'harissa spice',
  'horseradish',
  'italian seasoning',
  'mint',
  'mustard',
  'mustard powder',
  'nutmeg',
  'paprika',
  'smoked paprika',
  'star anise',
  'thai green curry paste',
  'thai red curry paste',
  'thyme',
  'vanilla extract',
  'vinegar',
  'white wine vinegar',
  'worcestershire sauce',
];

export const oilsAndFatsKeywords = [
  'butter',
  'ghee',
  'olive oil',
  'vegetable oil',
  'sunflower oil',
  'coconut oil',
  'canola oil',
  'sesame oil',
  'mustard oil',
  'almond oil',
  'lard',
  'margarine',
  'peanut oil',
  'coconut milk',
  'creamed corn',
  'cod liver oil',
  'shortening',
  'duck fat',
  'bacon fat',
  'butter oil',
];

export const fishAndSeafoodKeywords = [
  'salmon',
  'haddock',
  'cod',
  'king prawns',
  'tuna',
  'mussels',
  'sardines',
  'smoked salmon',
  'squid',
  'octopus',
  'scallops',
  'trout',
  'mackerel',
  'anchovies',
  'monkfish',
  'crab',
  'lobster',
  'shrimp',
  'calamari',
];

export const sweetenersAndSugarsKeywords = [
  'brown sugar',
  'demerara sugar',
  'granulated sugar',
  'maple syrup',
  'golden syrup',
  'molasses',
  'honey',
  'stevia',
  'agave syrup',
  'icing sugar',
  'powdered sugar',
  'caster sugar',
  'corn syrup',
  'dark brown sugar',
  'light brown soft sugar',
  'coconut sugar',
  'muscovado sugar',
  'dark chocolate chips',
  'milk chocolate',
  'white chocolate chips',
  'sweetener',
];

export const miscellaneousKeywords = [
  'flour',
  'eggs',
  'egg yolks',
  'egg whites',
  'baking powder',
  'bread',
  'condensed milk',
  'sourdough',
  'panko breadcrumbs',
  'bagels',
  'tortilla wraps',
  'meringue nests',
  'shortcrust pastry',
  'puff pastry',
  'yeast',
  'plain flour',
  'self-raising flour',
  'naan bread',
  'buckwheat',
];
